//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FP_DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Boleta
    {
        public string num_boleta { get; set; }
        public System.DateTime fecha { get; set; }
        public string cod_empl { get; set; }
        public string cod_cli { get; set; }
        public string num_ordenpedido { get; set; }
        public int subtotal { get; set; }
        public Nullable<int> descuento { get; set; }
        public int total { get; set; }
    
        public virtual OrdenPedido OrdenPedido { get; set; }
    }
}
