//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FP_DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleOrdenPedido
    {
        public string num_ordenp { get; set; }
        public string cod_pro { get; set; }
        public string nom_pro { get; set; }
        public Nullable<decimal> cantidad { get; set; }
        public Nullable<decimal> precio_venta { get; set; }
        public Nullable<decimal> importe { get; set; }
    
        public virtual Producto Producto { get; set; }
    }
}
