//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FP_DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public string cod_usu { get; set; }
        public string cod_emp { get; set; }
        public string nivel_usu { get; set; }
        public string nom_usu { get; set; }
        public string password { get; set; }
        public string activo { get; set; }
    
        public virtual Empleado Empleado { get; set; }
    }
}
